name: Run tests with Gradle

on:
  push:
  pull_request:
    branches:
      - develop

permissions:
  contents: read

env:
  java_version: '17'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java_version }}
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run tests
        run: ./gradlew test

  publish:
    needs:
      - test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java_version }}
          distribution: 'temurin'
          cache: 'gradle'
      - name: Publish plugin
        run: ./gradlew :thrift:publishPlugin
        env:
          JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
